package com.lazygeniouz.roomdb_practise.diff_util

import androidx.recyclerview.widget.DiffUtil
import com.lazygeniouz.roomdb_practise.databse.room.TestDao
import com.lazygeniouz.roomdb_practise.databse.room.TestEntity

/**
 * Helper class to implement [DiffUtil.Callback]
 *
 * We use the [TestEntity.uid] as a point of comparison between the old & new items,
 * because there is a rare chance that the first name or even the last name might be the same.
 *
 * This wouldn't happen with the **uid** as it is **PrimaryKey** & **autoGenerated** by RoomDao ([TestDao])
 */
class TestEntityDiffUtil(
    private val oldList: List<TestEntity>,
    private val newList: List<TestEntity>
) :
    DiffUtil.Callback() {

    override fun getOldListSize(): Int = oldList.size

    override fun getNewListSize(): Int = newList.size

    override fun areItemsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean {
        return oldList[oldItemPosition].uid == newList[newItemPosition].uid
    }

    override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean {
        return oldList[oldItemPosition].hashCode() == newList[newItemPosition].hashCode()
    }
}